2014/04/07 11:28:58 [error] 2379#0: *1 connect() to unix:///run/uwsgi/app/flask3/socket failed (111: Connection refused) while connecting to upstream, client: 192.168.1.140, server: flask3.local, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///run/uwsgi/app/flask3/socket:", host: "flask3.local"
2014/04/07 11:37:03 [error] 2393#0: *1 upstream prematurely closed connection while reading response header from upstream, client: 192.168.1.140, server: flask3.local, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///run/uwsgi/app/flask3/socket:", host: "flask3.local"
2014/04/07 11:46:04 [error] 2393#0: *3 upstream prematurely closed connection while reading response header from upstream, client: 192.168.1.140, server: flask3.local, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///run/uwsgi/app/flask3/socket:", host: "flask3.local"
